### PR TITLE
Add gallery page

### PR DESCRIPTION
**Pull request by Angel-AG**
Display a variety of photos. Each one with its respective alt.

### CODE REVIEW

**Review by akihiroota87 — APPROVED** [review]
Looks good to me! 

One thing I noticed: there seems to be some repeated content across your HTML files. For example, the <head>, <div id="nav">, and <div id="footer"> seem to be the same for each of your HTML pages. I don't want to block your progress on this change, but it would be good to consider a follow-up change that reuses content so that you only have to declare <head>, <div id="nav">, and <div id="footer"> once.

**Comment by Angel-AG** [comment]
Hi! I can't see the examples you are referring to, but I can imagine which ones they are. (the nav, footer, etc?)
Yes, I was thinking about it, too. I'll start the refactoring of it after the last page is added (just one more).

Do you have any recommendations of how to reuse them?
I couldn't find a way to do it natively in HTML and I found some approaches using JS, JQuery, etc.

**Comment by akihiroota87** [comment]
Hi Angel,

Sorry about that, for some reason my comments didn't appear. I was referring to `<head>`,`<footer>`, and `<div id="nav">` (hopefully you can see them now). 

As far as recommendations, you're right that using JavaScript would be helpful. I suggest that you do some quick research and outline possible approaches in a design sketch. When you've considered a few approaches, feel free to ask Mark and me for a review. And if you can't find a solution, I'd be happy to give some suggestions afterward :)

**Comment by Angel-AG** [comment]
Perfect, thanks! I'll add it to my design sketch.
The refactoring will come later on another PR, stay tuned. ;)

**Review by mschillaci — APPROVED** [review]
Looks good to me!

**Pull request merged**
